# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(parsnip)
    library(recipes)
    library(stats)
    library(workflows)
}
b <- board_folder(path = "pins_r")
v <- vetiver_pin_read(b, "penguins_model", version = "20230802T073528Z-ae149")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
