# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(parsnip)
    library(recipes)
    library(stats)
    library(workflows)
}
#b <- board_folder(path = "pins_r")
b <- board_url("https://raw.githubusercontent.com/svensson-martin/mlops/master/pins_r/_pins.yaml")
v <- vetiver_pin_read(b, "penguins_model")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
